/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FasilitasRouteImport } from './routes/fasilitas'
import { Route as KamarIndexRouteImport } from './routes/kamar.index'
import { Route as KamarNomorRouteImport } from './routes/kamar.$nomor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FasilitasRoute = FasilitasRouteImport.update({
  id: '/fasilitas',
  path: '/fasilitas',
  getParentRoute: () => rootRouteImport,
} as any)
const KamarIndexRoute = KamarIndexRouteImport.update({
  id: '/kamar/',
  path: '/kamar/',
  getParentRoute: () => rootRouteImport,
} as any)
const KamarNomorRoute = KamarNomorRouteImport.update({
  id: '/kamar/$nomor',
  path: '/kamar/$nomor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fasilitas': typeof FasilitasRoute
  '/kamar/$nomor': typeof KamarNomorRoute
  '/kamar/': typeof KamarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fasilitas': typeof FasilitasRoute
  '/kamar/$nomor': typeof KamarNomorRoute
  '/kamar': typeof KamarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fasilitas': typeof FasilitasRoute
  '/kamar/$nomor': typeof KamarNomorRoute
  '/kamar/': typeof KamarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fasilitas' | '/kamar/$nomor' | '/kamar/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fasilitas' | '/kamar/$nomor' | '/kamar'
  id: '__root__' | '/' | '/fasilitas' | '/kamar/$nomor' | '/kamar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FasilitasRoute: typeof FasilitasRoute
  KamarNomorRoute: typeof KamarNomorRoute
  KamarIndexRoute: typeof KamarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fasilitas': {
      id: '/fasilitas'
      path: '/fasilitas'
      fullPath: '/fasilitas'
      preLoaderRoute: typeof FasilitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamar/': {
      id: '/kamar/'
      path: '/kamar'
      fullPath: '/kamar/'
      preLoaderRoute: typeof KamarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamar/$nomor': {
      id: '/kamar/$nomor'
      path: '/kamar/$nomor'
      fullPath: '/kamar/$nomor'
      preLoaderRoute: typeof KamarNomorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FasilitasRoute: FasilitasRoute,
  KamarNomorRoute: KamarNomorRoute,
  KamarIndexRoute: KamarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
